# Datasource
spring.datasource.url=jdbc:mysql://localhost:3306/barber_elite?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Sao_Paulo
spring.datasource.username=root
spring.datasource.password=Deusmeu19
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA (dev only - mostra SQL)
spring.jpa.show-sql=true

# Logging (dev verbose)
logging.level.com.barber.elite=DEBUG
logging.level.org.springframework.security=DEBUG